version: "2"
services:
  api:
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

  database:
    build: ./database
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --mysql-native-password=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  backend:

