version: "2"
services:
  api:
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

  database:
    image: mysql:8.4.3
    networks:
      - backend
    environment:
      MYSQL_USER: springstudnet
      MYSQL_PASSWORD: springstudnet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database_name # should this be here??
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "springstudnet", "-pspringstudnet"]
      interval: 30s
      timeout: 10s
      retries: 5
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

networks:
  backend:
