version: "2"
services:
  api:
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

  database:
    image: mysql:8.4.3
    networks:
      - backend
    environment:
      MYSQL_USER: springstudnet
      MYSQL_PASSWORD: springstudnet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database_name
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  backend:
